# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Linus-branch
- main

pr:
- Linus-branch
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Node.js_CI
  displayName: 'Node.js CI'
  strategy:
    matrix:
      node-version: ['18.x']
  
  steps:
  - checkout: self
  
  - task: UseNode@1
    displayName: 'Setup Node.js'
    inputs:
      version: ${{ matrix.node-version }}
      checkLatest: true
      addToPath: true
      cache: 'npm'
  
  - script: npm ci
    displayName: 'Install Dependencies'
  
  - script: nohup npm start &
    displayName: 'Start Application'
  
  - script: npm run test-cypress
    displayName: 'Run Cypress Tests'

