Feature: Explore Different Locations

  Scenario Outline: Visit Various Locations(<name>)
    Given I am at the <name> place
    Then I should see a <description>
    And I should see the correct <image>

    Examples:
      | name                          | description                                                                                                                                                                                                                                                                                                                                  | image                        |
      | 'locations/cafe.json'         | "You are standing outside the Cloud Forest Cafe. The sun is shining."                                                                                                                                                                                                                                                                        | 'imgs/cloud-forest-cafe.jpg' |
      | 'locations/cafe-inside.json'  | "You are in the Cloud Forest Cafe. People are reading, talking and drinking coffee. Mmm... Coffee... The barrista says:\"How about an espresso? It's only $5.\""                                                                                                                                                                             | 'imgs/inside-cafe.jpg'       |
      | 'locations/music.json'        | "A guitarist and sax player makes som funky noise.The guitarist doesn't sing too well though."                                                                                                                                                                                                                                               | 'imgs/music-scene.jpg'       |
      | 'locations/bar.json'          | "You are in a crowded bar where everyone is friendly. But no coffee in sight. Everyone's drinking beer."                                                                                                                                                                                                                                     | 'imgs/bar.jpg'               |
      | 'locations/street.json'       | "You are on an empty street. Not much action around here."                                                                                                                                                                                                                                                                                   | 'imgs/street.jpg'            |
      | 'locations/country-side.json' | "You walk and walk. Now you're out in the contry-side. Just great. No coffee here..."                                                                                                                                                                                                                                                        | 'imgs/country-side.jpg'      |
      | 'locations/dead.json'         | "You health has deteriorated too much - you feel almost dead.Find a caffeine-detox clinic?"                                                                                                                                                                                                                                                  | 'imgs/dead.jpg'              |
      | 'locations/win.json'          | "Yes! You feel alive and pumping. Full of caffeine! You feel like... like... Luke Skywalker!"                                                                                                                                                                                                                                                | 'imgs/win.jpg'               |
      | 'locations/help.json'         | "You're a hipster. And you love iThings and your cool bag. But right now you're almost broke. And that's bad. Because you're an Espresso Addict too, a caffeine junkie. You need your fix - 5 cups of espresso. Otherwise you will start to feel really shaky... Really soon! So go get your fix... Lurk around and wait for opportunities!" | 'imgs/help.jpg'              |