name: Node.js CI

on:
  push:
    branches: [Linus-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci

      - name: Install live-server
        run: npm install -g live-server

      - run: nohup node index.js

      - name: Start Live Server
        run: live-server --port=5500 --entry-file=index.html

      - run: npm run test-cypress
